AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aw3-api

  AlgoWolf v3 copy trading application

Parameters:
  EnvironmentName:
    Type: String
  RepositoryBranch:
    Type: String
  TTL:
    Type: String
    Default: 0

Conditions:
  IsProd: !Equals [!Ref EnvironmentName, aw3-prod]
  IsDev: !Equals [!Ref EnvironmentName, aw3-dev]
  IsFeature: !Not [!Or [!Condition IsProd, !Condition IsDev]]

Resources:
  StackTTL:
    Type: AWS::SSM::Parameter
    Condition: IsFeature
    Properties:
      Name: !Sub /aw3/cfn/ttl/${AWS::StackName}
      Type: String
      Value: !Ref TTL
