name: AW3 Api CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Test code with pytest
      run: |
        pytest -c pytest.ini
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: >
      github.ref == 'refs/heads/main' 
      || github.ref == 'refs/heads/production'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install invoke
    - uses: aws-actions/setup-sam@v2
    - name: Set AWS Dev creds
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Deploy onto Dev
      if: github.ref == 'refs/heads/main'
      run: |
        invoke dev.deploy-global
        invoke dev.deploy
    - name: Set AWS Prod creds
      if: github.ref == 'refs/heads/production'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Deploy onto Prod
      if: github.ref == 'refs/heads/production'
      run: |
        invoke prod.deploy-global
        invoke prod.deploy
